[server]
lobby_name = "️Rayten"
[game]
hostname = "✨ RAYTEN | НОВОЕ КОМЬЮНИТИ"
desc = """
Rayten ждёт тебя!
- Море уникального контента: новые расы, режимы и антагонисты.
- Глубокая прокачка персонажа — твой выбор влияет на геймплей!
- Уютное RP-комьюнити без токсичности и с адекватной администрацией.
- Сервер с самым сильным античитом.

✨ Заходи к нам ✨
"""
soft_max_players = 40

[hub]
tags = "lang:ru,region:eu_e,rp:med"
advertise = true

[net]
tickrate = 30
max_connections = 80
port = 1212

[infolinks]
discord = "https://discord.gg/sRSGDyGPw2"
wiki = "https://rayten.ru/"
appeal = "https://discord.com/channels/1236324156165980311/1236381848909910126"
github = "https://github.com/RaytenCorp/Rayten"
bug_report = "https://discord.com/channels/1236324156165980311/1271239142944280671"

