- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleR1
  name: R1 Role
  components:
  - type: MindRole
    antagPrototype: R1Antag
    roleType: SoloAntagonist
    exclusiveAntag: true
    antag: true
  - type: R1Role
  - type: RoleBriefing
    briefing: r1-role-briefing

# Лондонец
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleLondoner
  name: Лондонец
  components:
  - type: MindRole
    antagPrototype: Londoner
    exclusiveAntag: true
    subtype: roles-antag-londoner-name
  - type: LondonerRole

# чумной доктор
- type: entity
  parent: BaseMindRoleAntag
  id: MindRolePlagueDoctor
  name: Чумной доктор
  components:
  - type: MindRole
    antagPrototype: PlagueDoctor
    subtype: role-subtype-plague-doctor
  - type: PlagueDoctorRole