- type: job
  id: SecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: JobSecurityCadet
  requirements:
    - !type:SpeciesRequirement
      species:
      - Vox
      inverted: true
    - !type:OverallPlaytimeRequirement
      time: 10h
    - !type:AgeRequirement
      requiredAge: 20
  startingGear: SecurityCadetGear
  icon: "JobIconSecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SecurityCadetGear
  equipment:
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite-MRP
    outerClothing: ClothingOuterArmorBasic
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: SecurityCadetChameleonOutfit
  job: SecurityCadet
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetBasic
    eyes: ClothingEyesHudSecurity
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckScarfStripedRed
    belt: ClothingBeltSecurity
    gloves: ClothingHandsGlovesColorBlack
