- type: randomHumanoidSettings
  id: VisitorSeniorCooker
  parent: EventHumanoid
  speciesBlacklist:
    - Diona
    - Moth
    - Arachnid
    - Dwarf
    - Vox
    - Reptilian
    - Vulpkanin
  components:
    - type: GhostRole
      name: ghost-role-information-cooker-name
      description: ghost-role-information-cooker-description
      rules: ghost-role-information-freeagent-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes:
        - VisitorWalter
      roleLoadout: [ RoleSurvivalExtended ]
    - type: Skill
      basicSkills:
        Medicine: 3
        Engineering: 3
      easySkills:
      - Piloting
      - MusInstruments
      - Botany
      - Bureaucracy
      - Research

- type: randomHumanoidSettings
  id: VisitorJuniorCooker
  parent: EventHumanoid
  speciesBlacklist:
    - Diona
    - Moth
    - Arachnid
    - Dwarf
    - Vox
    - Reptilian
    - Vulpkanin
  components:
    - type: GhostRole
      name: ghost-role-information-cooker-name
      description: ghost-role-information-cooker-description
      rules: ghost-role-information-freeagent-rules
      raffle:
        settings: short
    - type: Loadout
      prototypes:
        - VisitorJessy
      roleLoadout: [ RoleSurvivalExtended ]
    - type: Skill
      basicSkills:
        Weapon: 3
        Medicine: 2
      easySkills:
      - Piloting
      - MusInstruments
      - Botany
      - Bureaucracy
      - Research