- type: job
  id: CBURN
  name: job-name-cburn
  description: job-description-cburn
  playTimeTracker: JobCBURN
  setPreference: false
  startingGear: CBURNGear
  icon: "JobIconCBURN"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ClothingShoesTacticalBoots
    id: CBURNPDA
    pocket1: RadioHandheldSecurity
    pocket2: GlowstickYellow
    belt: WeaponAdvancedLaser
  storage:
    back:
    - BoxMagazineShotgunIncendiary
    - GrenadeIncendiary
    - PillAmbuzolPlus
    - PillAmbuzol
    - PillAmbuzol
    - PillAmbuzol
    - MeleeWeaponPlasmaSword
  inhand:
  - WeaponShotgunBulldog

- type: chameleonOutfit
  id: CBURNChameleonOutfit
  job: CBURN
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetCBURN
    neck: ClothingNeckScarfStripedBrown
